/*
 * {{PROJECT_NAME}}
 * Generated by make.universal
 *
 * Version : {{VERSION}}
 * Author  : {{AUTHOR}}
 * License : {{LICENSE}}
 */
#include <iostream>
int main(int argc, char* argv[])
{
    std::cout << "{{PROJECT_NAME}} v{{VERSION}}" << std::endl;
    std::cout << "Built with make.universal" << std::endl;
    return 0;
}
