/*
 * ==========================================================
 * {{PROJECT_NAME}}
 * Generated by make.universal
 *
 * Version : {{VERSION}}
 * Author  : {{AUTHOR}}
 * License : {{LICENSE}}
 * ==========================================================
 */
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;
    printf("%s v%s\n", "{{PROJECT_NAME}}", "{{VERSION}}");
    printf("Built with make.universal\n");
    return EXIT_SUCCESS;
}
