# core.py
import os

def create_project(name):
    if not name:
        print("Missing project name")
        return

    os.makedirs(name, exist_ok=True)

    with open(f"{name}/README.md", "w") as f:
        f.write(f"# {name}\nGenerated by makeuniversal CLI")

    print(f"✔ Created project: {name}")


def deploy_project(name):
    print(f"🚀 Deploying {name}")
    print("✔ Docker build ready")
    print("✔ K8s config generated")
