import fs from "fs";

export function createProject(name) {
  if (!name) {
    console.log("❌ Project name required");
    return;
  }

  fs.mkdirSync(name, { recursive: true });

  fs.writeFileSync(
    `${name}/README.md`,
    `# ${name}\nGenerated by makeuniversal CLI`
  );

  console.log(`✔ Web4 project created: ${name}`);
}

export function deployProject(name) {
  if (!name) {
    console.log("❌ Project name required");
    return;
  }

  console.log(`🚀 Deploying Web4 project: ${name}`);
  console.log("✔ Docker build triggered");
  console.log("✔ Kubernetes manifest ready");
}
